### ISSUE TITLE
FINALLY! Thank you SOOOO much!!!!

### ISSUE THREAD

**Issue by cybert79** [danielrivard/homeassistant-innova#1]
Finally an integration that works for innova!!!!

**Comment by Robby-Swartenbroekx** [comment]
Does it work stable with you? I'm pretty sure the issue lies with the innova units and not with this plugin.

**Comment by cybert79** [comment]
Well, it works for 3 hours now :)

I dit put  scan_interval on 1200, as if you do it to much, the innova wifi module crashes, and then you need to pull out the power cable of the unit to reset it.

**Comment by Robby-Swartenbroekx** [comment]
great tip about changing the scan interval to 20 minutes. That wifi chip is indeed very fragile, even with all their apps it only works half the time.

**Comment by danielrivard** [comment]
Thanks guys! Glad it helps some other people than me. 

I have been running the integration for 2-3 months now. It does have some issues, the webserver of the unit is very finicky and will fail on some commands relatively frequently. In my case, I have never needed to cut its power off though. Sometimes it is homeassistant itself that seems to get stuck with a bad status update, restarting HA often fixes it. So there might be some issues with the integration itself. This is my first integration and am fairly new to the HA world too, and am still learning the subtleties of it.

Also, I have just enabled the discussions tab on the repo, so rather than opening issues, you can use that forum to discuss  topics that are not actual issues.
https://github.com/danielrivard/homeassistant-innova/discussions
